# KnexChain Core Sponsorship
# Support the world's first Proof-of-Bandwidth blockchain development

# Primary sponsorship via Buy Me a Coffee
buy_me_a_coffee: knexcoin

# Custom sponsorship links
custom: 
  - 'https://buymeacoffee.com/knexcoin'
